# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker images

on:
  # Trigger the workflow on new releases
  release:
    types: [published]
  
  # Allow manual execution from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name: [notesnook-sync, identity, sse]
        include:
          - image_name: notesnook-sync
            dockerfile: ./Notesnook.API/Dockerfile

          - image_name: identity
            dockerfile: ./Streetwriters.Identity/Dockerfile

          - image_name: sse
            dockerfile: ./Streetwriters.Messenger/Dockerfile
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # Setup Buildx
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construct the full image name for use in subsequent steps
      - name: Set full image name
        run: echo "IMAGE_PATH=ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}" >> $GITHUB_ENV

      # Pull previous image from ghcr.io to use it as cache to improve the image build time.
      - name: docker pull cache image
        continue-on-error: true
        run: docker pull ${{ env.IMAGE_PATH }}:latest

      # Setup QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PATH }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.IMAGE_PATH }}:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.IMAGE_PATH }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
